name: Java CI with Gradle
on:
  push:
    branches: [ develop ]
    tags: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build --scan
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u="$DOCKER_USERNAME" -p="DOCKERHUB_TOKEN" docker.io
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag systemedz/entsoe-market-data-service:latest
      - name: Publish Docker image to Docker Hub
        run: docker push systemedz/entsoe-market-data-service:latest